[package]
name = "teemiao"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
clap-verbosity-flag = "2.2.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
