[package]
name = "teemiao"
version = "0.1.1"
edition = "2021"
description = "Teemiao is a set of convenient tools for building other applications."
license = "Apache-2.0"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.21", features = ["derive"] }
clap-verbosity-flag = "2.2.3"
env_logger = "0.11.5"
gix = "0.67.0"
log = "0.4.22"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.133"
